source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'babel-transpiler'
gem 'dotenv-rails'
gem 'heartwood-uploader', path: File.expand_path('../../', __dir__)
gem 'jquery-rails'
gem 'sqlite3'
gem 'sprockets', '4.0.0.beta7'
